# Generated by Django 5.2 on 2026-02-27 17:08

import apps.pdm.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('caminho_relativo', models.CharField(max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'unique_together': {('projeto', 'caminho_relativo')},
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_versao', models.PositiveIntegerField()),
                ('arquivo', models.FileField(upload_to=apps.pdm.models.document_version_path)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('checksum_hash', models.CharField(max_length=64)),
                ('tamanho_bytes', models.BigIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pdm.document')),
            ],
            options={
                'verbose_name': 'Versão do Documento',
                'verbose_name_plural': 'Versões dos Documentos',
                'ordering': ['-numero_versao'],
                'unique_together': {('documento', 'numero_versao')},
            },
        ),
    ]
